### ISSUE TITLE
wget url to supplementary data seems not up to date

### ISSUE THREAD

**Issue by LaurenzEngel** [NKI-CCB/TRANSACT_manuscript#14]
Hello, thank you very much for your work, 

In the download_TCGA script, an error occurs after running the wget command 

`ERROR 403: Forbidden`

It seems the URL to the supplemental data is not up to date.

**Comment by saroudant** [comment]
Hi @LaurenzEngel,

Thanks a lot for your interest in our work. Unfortunately, there is no permanent link to download the supplementary data from [Ding et al, 2016, Bioinformatics]. You can otherwise download the data from here: https://academic.oup.com/bioinformatics/article/32/19/2891/2196464#supplementary-data
I will add a note in the README and the bash script to make that clear. Sorry for the inconvenience.
Does that answer your question? Please let me know if anything else is unclear.

Best regards,
Soufiane

**Comment by LaurenzEngel** [comment]
Yes that answers my question. 

Thank you for the quick reply.

Best regards, 
Laurenz
